const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  registerPuntori: async (formData) => ipcRenderer.invoke('registerPuntori', formData),
  getAllPuntor: async() => ipcRenderer.invoke('getAllPuntor'),
  addPllake: async (formData) => ipcRenderer.invoke('addPllake', formData),
  addProduct: async (formData) => ipcRenderer.invoke('addProduct', formData),
  getTodayProduct: async () => ipcRenderer.invoke('getTodayProduct'),
  searchProduct: async(data) => ipcRenderer.invoke('searchProduct', data),
  deleteProduct: async(data) => ipcRenderer.invoke('deleteProduct', data),
  isTile: async(data) => ipcRenderer.invoke('isTile', data),
  editProduct: async (formData) => ipcRenderer.invoke('editProduct', formData),
  getTileData: async(data) => ipcRenderer.invoke('getTileData', data),
  editTile: async(formData) => ipcRenderer.invoke('editTile', formData),
  addClient: async(formData)=> ipcRenderer.invoke('addClient', formData),
  searchClient: async(data) => ipcRenderer.invoke('searchClient', data),
  addInvoice: async(formData) => ipcRenderer.invoke('addInvoice', formData),
  searchInvoices: async(formData) => ipcRenderer.invoke('searchInvoices', formData),
  printToPDF: async(htmlContent, options) => ipcRenderer.invoke('printToPDF', htmlContent, options),
  savePDF: async(pdfBuffer, filename) => ipcRenderer.invoke('savePDF', pdfBuffer, filename),
  getProductsInvoice: async (faturaID) => ipcRenderer.invoke('getProductsInvoice', faturaID),
  getDashboardData: async () => ipcRenderer.invoke('getDashboardData'),
  getInvoicesWithDebtById: async(klientiID) => ipcRenderer.invoke('getInvoicesWithDebtByID', klientiID),
  addPayment: async(formData) => ipcRenderer.invoke('addPayment', formData),
  getPaymentsToday: async() => ipcRenderer.invoke('getPaymentsToday'),
});