CREATE DATABASE IF NOT EXISTS arta-commerce;

USE arta-commerce;

CREATE TABLE IF NOT EXISTS Puntori(
    puntoriID INT AUTO_INCREMENT PRIMARY KEY,
    emriMbiemri VARCHAR(50) NOT NULL    
);

CREATE TABLE IF NOT EXISTS Klienti(
    klientiID INT AUTO_INCREMENT PRIMARY KEY,
    emriMbiemri VARCHAR(50) NOT NULL,
    searchName VARCHAR(50) NOT NULL,
    telefoni VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Produkt(
    produktID INT AUTO_INCREMENT PRIMARY KEY,
    emriProduktit VARCHAR(100) NOT NULL,
    searchName VARCHAR(100) NOT NULL,
    cmimi DECIMAL(10,2) NOT NULL,
    sasia INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE  TABLE IF NOT EXISTS Pllaka(
    produktID INT PRIMARY KEY,
    gjatesia DECIMAL(10,2) NOT NULL,
    gjeresia DECIMAL(10,2) NOT NULL,
    siperfaqja DECIMAL(10,2) AS (gjatesia * gjeresia) STORED,
    pllakaNeKuti INT NOT NULL,
    FOREIGN KEY(produktID) REFERENCES Produkt(produktID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Fatura(
    faturaID INT AUTO_INCREMENT PRIMARY KEY,
    shumaPaguar DECIMAL(10,2) NOT NULL,
    totaliPaZbritje DECIMAL(10,2) NOT NULL,
    zbritja DECIMAL(10,2) NOT NULL,
    totali DECIMAL (10,2) AS (totaliPaZbritje - zbritja) STORED,
    borxhi DECIMAL(10,2) AS (totaliPaZbritje - zbritja - shumaPaguar) STORED,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    puntoriID INT NOT NULL,
    klientiID INT,
    FOREIGN KEY(klientiID) REFERENCES Klienti(klientiID) ON DELETE CASCADE,
    FOREIGN KEY(puntoriID) REFERENCES Puntori(puntoriID)
);

CREATE TABLE IF NOT EXISTS ProduktiFatura(
    produktiFaturaID INT AUTO_INCREMENT PRIMARY KEY,
    NrList INT NOT NULL,
    sasia INT NOT NULL,
    cmimiNjesi DECIMAL(10,2) NOT NULL,
    cmimiTotal DECIMAL(10,2) NOT NULL,
    njesiaMatese VARCHAR(20) NOT NULL,
    produktID INT NOT NULL,
    faturaID INT NOT NULL,
    FOREIGN KEY (produktID) REFERENCES Produkt(produktID),
    FOREIGN KEY (faturaID) REFERENCES Fatura(faturaID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Demet(
    DemeID INT AUTO_INCREMENT PRIMARY KEY,
    produktID INT NOT NULL,
    sasiaDemtuar INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    puntoriID INT NOT NULL,
    FOREIGN KEY (puntoriID) REFERENCES Puntori(puntoriID) ON DELETE CASCADE,
    FOREIGN KEY (produktID) REFERENCES Produkt(produktID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Pagesa(
    pagesaID INT AUTO_INCREMENT PRIMARY KEY,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    shumaPaguar DECIMAL(10,2) NOT NULL,
    faturaID INT NOT NULL,
    FOREIGN KEY (faturaID) REFERENCES Fatura(faturaID) ON DELETE CASCADE
);